[package]
name = "tendrl_core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
nostrdb = { workspace = true }
enostr = { workspace = true }
nostr = { workspace = true }
notedeck = { workspace = true }
notedeck_ui = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
hex = "0.4"
profiling = { version = "1", default-features = false }
